version: '3.9'

services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      mqtt_network:


  edge:
    build: ./code
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER: tcp://mqtt:1883
      MQTT_BROKER_PORT: 1883
      MQTT_DELAY: 1000
    networks:
      mqtt_network:


networks:
  mqtt_network: